# Generated by Django 5.1.4 on 2025-01-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='nama_status',
            field=models.CharField(max_length=255),
        ),
    ]
